version: "3.7"

services:
 eureka-server:
   container_name: eureka
   image: mcicolella/eureka-server:latest
   ports:
   - "8761:8761"
   networks:
      - backend  
   
 zuul-gateway:
   container_name: zuul-gateway
   image: mcicolella/zuul-gateway:latest
   hostname: "zuul-gateway"
   ports:
   - "8085:8085"
   environment:
   - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
   - eureka.instance.preferIpAddress=true
   depends_on:
     - eureka-server
   networks:
      - backend  

 microservice-demo:
   container_name: microservice
   image: mcicolella/microservice-demo:latest
   hostname: "microservice"
   ports:
   - "8080:8080"
   environment:
   - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
   - eureka.instance.preferIpAddress=true
   depends_on:
     - eureka-server
   networks:
      - backend  

networks:
  backend:
